### PR TITLE
@drizzle/store extending .npmignore

### PR DESCRIPTION
**Pull request by MrRefactoring**

### CODE REVIEW

**Comment by adrianmcli** [comment]
Thanks for the PR! I recall from a while back that we actually changed this to include the `src` for some reason. I can't remember what that reason is though, so maybe give us a bit of time to look into this. Thanks again!

**Comment by adrianmcli** [comment]
Found it! We need `src` to be published for React Native support: https://github.com/trufflesuite/drizzle-legacy/issues/130

But that being said, we could take out a bunch of the other stuff.

**Comment by MrRefactoring** [comment]
> Found it! We need `src` to be published for React Native support: [trufflesuite/drizzle-legacy#130](https://github.com/trufflesuite/drizzle-legacy/issues/130)
> 
> But that being said, we could take out a bunch of the other stuff.

This is a good use case. Remove src from npmignore

**Comment by adrianmcli** [comment]
lgtm, thanks!

**Pull request merged**
